GET http://localhost:3001/gtcs HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3001/gtcs HTTP/1.1
Content-Type: application/json

{
  "playlist": "AI Tutorials",
  "title": "Introduction to GenAI",
  "tags": [
    "AI",
    "Machine Learning",
    "GenAI"
  ],
  "duration": 3600,
  "last_viewed": "2024-10-19T15:30:00"
}


### 

