"use client";

import React, { useEffect, useState } from "react";
import ReactFlow, { Controls, Background } from "@xyflow/react";
import dependencyGraph from "./dependencyGraph"; // Import the JSON file generated by the script

const DependencyGraph = () => {
  const [nodes, setNodes] = useState([]);
  const [edges, setEdges] = useState([]);

  useEffect(() => {
    setNodes(dependencyGraph.nodes);
    setEdges(dependencyGraph.edges);
  }, []);

  return (
    <div style={{ height: "100vh" }}>
      <ReactFlow nodes={nodes} edges={edges} fitView>
        <Controls />
        <Background />
      </ReactFlow>
    </div>
  );
};

export default DependencyGraph;
